version: '3.7'

services:
  web:
    build: ./
    container_name: dfa_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: dfa_db
    volumes:
      - .:/var/lib/postgresql
    env_file:
      - ./.env
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: dfa_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  audio_library_postgres_data: